first attempt at passing the junit file for errors

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -98,6 +98,18 @@ jobs:
     displayName: 'Code coverage and JUnit report output'
     condition: always()
 
+
+  - bash: |
+      # Strip out when error and failure = 0 and count the number of times it does not.
+      error_count=$(sed 's/errors="0"//' junit_raw.xml | grep --count errors=)
+      failure_count=$(sed 's/failues="0"//' junit_raw.xml | grep --count failures=)
+      echo "Non zero errors: "$error_count
+      echo "Non zoro failures: "$failure_count
+      exit $(($error_count + $failure_count))
+    displayName: 'Check for errors & Failures in JUnit file'
+    condition: always()
+
+
   - bash: |
       git clone https://datashield:$(GHPAT)@github.com/datashield/testStatus.git testStatus
 
